### ISSUE TITLE
Improved markdown experience in Free2z.

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/free2z#7]
[Free2z](free2z.com) is simply **excellent**, but there are people who find it **difficult** to use the **Markdown language**.

To solve this problem you can add a bar with shortcuts to the different formats.

![FQtg1IoXsAACOhA](https://user-images.githubusercontent.com/37910384/164335023-1f488541-9523-4b69-ab54-81ce45bf75c4.jpg)

The image shows a design as a _[reference](https://forum.zcashcommunity.com/)_, the idea is to have a bar that **facilitates** the use of markdown to users who do not know how to use the language or even if they know how to use it, they **prefer** a feature like the one suggested.

Surely developers will be able to better materialize the idea and design, either with a bar, a contextual menu, commands, etc.

GitHub also has a similar feature.
![BAR](https://user-images.githubusercontent.com/37910384/164335112-8f8e9710-bb21-4b04-b6f0-9c5e002403eb.png)
**¡Thanks for such a great option in the Zcash ecosystem - long live Free2z!**

**Comment by skyl** [comment]
Great idea, yeah! Looking at this github input widget I'm typing into right now I realize that it's a perfect model for where we want to go. Free2z has different options like embeds and math instead of eg links to other issues or uploads. But, the model I think is perfect - no attempt to make a WYSIWYG or anything too complicated, but even people who don't know any markdown can do (almost) all the possible functions in a very user-friendly way.

**Comment by Edicksonjga** [comment]
I am very glad you liked it, yes the solution presented by GitHub could be the same for Free2z and it is the most basic and essential that every user needs to create their blogs.

WYSIWYG = IMAGINATION. 😀😀😀

**Comment by skyl** [comment]
This gets pretty close but it's not quite a drop-in solution for some reason; so, we'll check later. Maybe @birdify could help. There is something clashing with our existing styles

https://github.com/uiwjs/react-md-editor

<img width="556" alt="Screen Shot 2022-04-20 at 6 37 52 PM" src="https://user-images.githubusercontent.com/61438/164354495-60c6a76d-5262-4dca-b68a-e9400774a4d7.png">

**Comment by birdify** [comment]
@skyl this looks pretty sweet, let me see if I can polish this up a bit

**Comment by skyl** [comment]
¿pruebala ahora? @Edicksonjga

**Comment by skyl** [comment]
I still like github's better:

- bigger icons
- text functions grouped
- cool extensions
- refined theme touches

But:

On Free2z you can swipe on mobile which is kinda fire. In the future we can add shortcuts to math and embeds and graphs and many more sweet things, ipython notebooks... anything that can be done with remark and rehype.

**Comment by skyl** [comment]
::embed[https://twitter.com/free2zcash/status/1517070062108262401]

**Comment by skyl** [comment]
I'll leave this open for now and maybe we'll take another pass at it for the F2Z customization and syntax highlighting. Maybe we'll create new issues for those things and close this one later.

**Comment by skyl** [comment]
on second thought, I made this follow up note for a second round: https://github.com/free2z/free2z/projects/1#card-80974547 and will close this issue as a good first pass for what was asked for.

**Comment by skyl** [comment]
fixed
